const GameActionTypes = {
    SET_GAME_LOADING: 'SET_GAME_LOADING',
    SET_GAME_SUCCESS: 'SET_GAME_SUCCESS',
    SET_GAME_ERROR: 'SET_GAME_ERROR',
    SET_DRAW_ERROR: 'SET_DRAW_ERROR',
    SET_CHANCES_ERROR: 'SET_CHANCES_ERROR',
    SET_GAME_SPEED: 'SET_GAME_SPEED',
    UPDATE_GAME_REMAINING: 'UPDATE_GAME_REMAINING',
    RESET_GAME_SUCCESS: 'RESET_GAME_SUCCESS',
    SET_COUNTING: 'SET_COUNTING',
    RESET_GAME: 'RESET_GAME',
    UPDATE_REM_WITH_REQ: 'UPDATE_REM_WITH_REQ'
}

export default GameActionTypes;