const UserActionTypes = {
    SET_USER_NAME: 'SET_USER_NAME',
    UPDATE_USER_NAME: 'UPDATE_USER_NAME',
    RESET_USER: 'RESET_USER',
    INCREASE_USER_V: 'INCREASE_USER_V',
    INCREASE_POINTS: 'INCREASE_POINTS'
}

export default UserActionTypes;