const PlayActionTypes = {
    SET_CLAIMS_SUCCESS: 'SET_CLAIMS_SUCCESS',
    SET_CLAIMING: 'SET_CLAIMING',
    SET_CLAIMING_ERROR: 'SET_CLAIMING_ERROR',
    SET_CLAIMED_SUCCESS: 'SET_CLAIMED_SUCCESS',
    RESET_CLAIMED_COUNT: 'RESET_CLAIMED_COUNT',
    SET_BOGUS_CLAIM: 'SET_BOGUS_CLAIM',
    RESET_CLAIMS: 'RESET_CLAIMS'
}

export default PlayActionTypes;