const PlayActionTypes = {
    SET_PLAY_SUCCESS: 'SET_PLAY_SUCCESS',
    SET_PLAY_ERROR: 'SET_PLAY_ERROR',
    RESET_PLAY: 'RESET_PLAY',
    SET_CLAP_LOADING: 'SET_CLAP_LOADING',
    ADD_TO_CLAPPED: 'ADD_TO_CLAPPED',
    RESET_CLAPPED: 'RESET_CLAPPED'
}

export default PlayActionTypes;